### ISSUE TITLE
pyarmor error

### ISSUE THREAD

**Issue by L-O-G-A-N** [JinxTheCatto/Stellite#2]
Traceback (most recent call last):
  File "C:\Users\Logan\Desktop\Stellite-master\bot.py", line 2, in <module>
    from pyarmor_runtime_000000 import __pyarmor__
  File "C:\Users\Logan\Desktop\Stellite-master\pyarmor_runtime_000000\__init__.py", line 2, in <module>
    from .pyarmor_runtime import __pyarmor__
ImportError: DLL load failed while importing pyarmor_runtime: The specified module could not be found.

first run, havent changed anything, already ran setup

**Comment by JinxTheCatto** [comment]
Join the discord and read common errors channel
